# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddJob.ui'
#
# Created: Tue May 14 14:44:13 2013
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(727, 582)
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Add Job", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(0, 540, 721, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 711, 161))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayoutWidget = QtGui.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 691, 141))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setText(QtGui.QApplication.translate("Dialog", "Job Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.jobNameWidget = QtGui.QLineEdit(self.formLayoutWidget)
        self.jobNameWidget.setObjectName(_fromUtf8("jobNameWidget"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.jobNameWidget)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Job Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.jobDescriptionWidget = QtGui.QPlainTextEdit(self.formLayoutWidget)
        self.jobDescriptionWidget.setObjectName(_fromUtf8("jobDescriptionWidget"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.jobDescriptionWidget)
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 180, 711, 361))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.frame_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 341, 311))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setRowWrapPolicy(QtGui.QFormLayout.WrapAllRows)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Multiple CPUs:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.multiCpuWidget = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.multiCpuWidget.setText(_fromUtf8(""))
        self.multiCpuWidget.setObjectName(_fromUtf8("multiCpuWidget"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.multiCpuWidget)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Required OS:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.reqOSWidget = QtGui.QComboBox(self.formLayoutWidget_2)
        self.reqOSWidget.setObjectName(_fromUtf8("reqOSWidget"))
        self.reqOSWidget.addItem(_fromUtf8(""))
        self.reqOSWidget.setItemText(0, QtGui.QApplication.translate("Dialog", "Linux", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.reqOSWidget)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Min CPU Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.minCpuCountWidget = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.minCpuCountWidget.setObjectName(_fromUtf8("minCpuCountWidget"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.minCpuCountWidget)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Min Memory:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.minMemoryWidget = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.minMemoryWidget.setObjectName(_fromUtf8("minMemoryWidget"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.minMemoryWidget)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.pathWidget = QtGui.QPlainTextEdit(self.formLayoutWidget_2)
        self.pathWidget.setObjectName(_fromUtf8("pathWidget"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.pathWidget)
        self.formLayoutWidget_3 = QtGui.QWidget(self.frame_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(380, 40, 291, 311))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setRowWrapPolicy(QtGui.QFormLayout.WrapAllRows)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Required Programs:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.reqProgramsWidget = QtGui.QPlainTextEdit(self.formLayoutWidget_3)
        self.reqProgramsWidget.setObjectName(_fromUtf8("reqProgramsWidget"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.reqProgramsWidget)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Compiler:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.compilerWidget = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.compilerWidget.setObjectName(_fromUtf8("compilerWidget"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.compilerWidget)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Execution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.executeWidget = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.executeWidget.setObjectName(_fromUtf8("executeWidget"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.executeWidget)
        self.loadButton = QtGui.QPushButton(self.frame_2)
        self.loadButton.setGeometry(QtCore.QRect(10, 10, 131, 27))
        self.loadButton.setText(QtGui.QApplication.translate("Dialog", "Load from file...", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setObjectName(_fromUtf8("loadButton"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        pass

